version: '3'
services:
  atomly_surveyshark_redis:
    container_name: atomly_surveyshark_redis
    image: redis
    ports:
      - "${REDIS_CONTAINER_PORT}"
    # Setting the server password on start.
    command: redis-server --requirepass ${REDIS_PASSWORD} --port "${REDIS_PORT}"
