version: '3.4'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  local_redis:
    container_name: local_redis
    image: redis
    ports:
      - ${LOCAL_REDIS_CONTAINER_PORT}
    # Setting the server password on start.
    command: redis-server --requirepass ${LOCAL_REDIS_PASSWORD} --port ${LOCAL_REDIS_PORT}

  local_mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    entrypoint: [ "mongod", "--bind_ip_all", "--replSet", "rs0" ]
    profiles: # Way to disable service w/o commenting out.
      - DISABLED

  local_mongo_client:
    image: mongo
    depends_on:
      - local_mongodb
    volumes:
      - ./scripts:/scripts
    entrypoint:
      - ./scripts/initiate_mongo_replica_set_client.sh
    profiles: # Way to disable service w/o commenting out.
      - DISABLED

networks:
  default:
    name: localstack
